apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open-ondemand.fullname" . }}-shell-setup
data:

  {{ $counter := int64 1 }}
  {{ range .Values.clusters }}
  cluster{{ $counter }}.yml: |
    ---
    v2:
      metadata:
        title: {{ .cluster.name | quote }}
        priority: 2
      login:
        host: {{ .cluster.host | quote }}
    ---
  {{ add1 $counter }}
  {{ end }}
