apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open-ondemand.fullname" . }}-shell-setup
data:
  cluster1.yaml: |
    ---
    v2:
      metadata:
        title: "{{ .Values.cluster1.name }}"
        priority: 2
      login:
        host: "{{ .Values.cluster1.host }}"
    ---

  cluster2.yaml: |
    ---
    v2:
      metadata:
        title: "{{ .Values.cluster1.name }}"
        priority: 2
      login:
        host: "{{ .Values.cluster1.host }}"
    ---
